micronaut:
  application:
    name: catmania
  server:
    port: 8080
    cors:
      enabled: true
    configurations:
      webapp:
        allowedOrigins:
          - http://localhost:5173
        allowedMethods: [ GET, POST, PATCH, PUT, DELETE, OPTIONS ]
        allowedHeaders: [ Authorization, Content-Type, Accept ]
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_SECRET_BASE64:nBuayA0ZiqYK4tP82XxGS8kfJGxqtvI4wWwxRnTj0NY=}"
              base64-encoded: true
              jws-algorithm: HS256
        generator:
          access-token-expiration: 3600
datasources:
  default:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydb}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: postgres
    password: postgres
  bootstrap:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: postgres
    password: postgres

flyway:
  datasources:
    default:
      enabled: true
